
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = " ='d\x8d\xb7R\xb6\x1f=\x88\xbc_H\xec\x17"
    
_lr_action_items = {'STAR':([1,2,4,5,6,8,9,10,],[5,-5,-6,-3,5,5,5,-2,]),'SYMBOLS':([0,1,2,3,4,5,6,7,8,9,10,],[2,2,-5,2,-6,-3,2,2,2,2,-2,]),'PLUS':([1,2,4,5,6,8,9,10,],[7,-5,-6,-3,-4,7,-1,-2,]),'LPAREN':([0,1,2,3,4,5,6,7,8,9,10,],[3,3,-5,3,-6,-3,3,3,3,3,-2,]),'RPAREN':([2,4,5,6,8,9,10,],[-5,-6,-3,-4,10,-1,-2,]),'EMPTY':([0,1,2,3,4,5,6,7,8,9,10,],[4,4,-5,4,-6,-3,-4,4,4,-1,-2,]),'$end':([1,2,4,5,6,9,10,],[0,-5,-6,-3,-4,-1,-2,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'exp':([0,1,3,6,7,8,9,],[1,6,8,6,9,6,6,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> exp","S'",1,None,None,None),
  ('exp -> exp PLUS exp','exp',3,'p_exp_plus','C:\\Users\\user\\Dropbox\\Documents\\workspace\\Automata\\Reg2eNFA\\regLY.py',36),
  ('exp -> LPAREN exp RPAREN','exp',3,'p_exp_paren','C:\\Users\\user\\Dropbox\\Documents\\workspace\\Automata\\Reg2eNFA\\regLY.py',40),
  ('exp -> exp STAR','exp',2,'p_exp_star','C:\\Users\\user\\Dropbox\\Documents\\workspace\\Automata\\Reg2eNFA\\regLY.py',44),
  ('exp -> exp exp','exp',2,'p_exp_concat','C:\\Users\\user\\Dropbox\\Documents\\workspace\\Automata\\Reg2eNFA\\regLY.py',48),
  ('exp -> SYMBOLS','exp',1,'p_exp_sym','C:\\Users\\user\\Dropbox\\Documents\\workspace\\Automata\\Reg2eNFA\\regLY.py',52),
  ('exp -> EMPTY','exp',1,'p_exp_empty','C:\\Users\\user\\Dropbox\\Documents\\workspace\\Automata\\Reg2eNFA\\regLY.py',56),
]
